server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
   prefer-ip-address: true
   
spring:
 application:
    name: Hcl-Gateway
 cloud:
  gateway:
   routes:
       - id: student
         uri: lb://STUDENT-SERVICE	
         predicates:
         - Path=/student/**
       - id: course
         uri: lb://COURSE-SERVICE	 
         predicates: 
         - Path=/course/**